export const IS_LOADING_POST = 'IS_LOADING_POST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'

export const IS_ERROR_POST = 'IS_ERROR_POST'
export const POST_DATA_POST = 'POST_DATA_POST'
export const POST_DATA_POST_SUCCESS = 'POST_DATA_POST_SUCCESS'
export const PUT_DATA_POST_SUCCESS = 'PUT_DATA_POST_SUCCESS'
export const POST_DATA_POST_ERROR = 'POST_DATA_POST_ERROR'
export const POST_DATA_DELETE = ' POST_DATA_DELETE'
export const ORDER_POST = 'ORDER_POST'


export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'

export const IS_LOADING_COMMENTS = 'IS_LOADING_COMMENTS'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const IS_COMMENTS_ERROR = 'IS_COMMENTS_ERROR'
export const POST_DATA_COMMENT_SUCCESS = 'POST_DATA_COMMENT_SUCCESS'
export const PUT_DATA_COMMENT_SUCCESS = 'PUT_DATA_COMMENT_SUCCESS'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const ORDER_COMMENTS = 'ORDER_COMMENTS'

export const VOTE_SUCCESS_POST = 'VOTE_SUCCESS_POST'
export const VOTE_ERROR_POST = 'VOTE_ERROR_POST'

